#     _      _           _
#  __| | ___(_)_ __     | | __ _ _____   _
# / _` |/ _ \ | '_ \    | |/ _` |_  / | | |
#| (_| |  __/ | | | |   | | (_| |/ /| |_| |
# \__,_|\___|_|_| |_|___|_|\__,_/___|\__, |
#                  |_____|           |___/
#------------------------------------------

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# on_event = 'InsertCharPre'
# on_ft = 'snippet'
# depends = 'neosnippet-snippets'
# hook_source = '''
# source /Users/maedar/dotfiles/.config/nvim/neosnippet.rc.vim
# '''

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# depends = 'context_filetype.vim'
# on_event = 'InsertEnter'
# on_i = 1
# hook_source = '''
# let g:deoplete#enable_at_startup = 1
# source /Users/maedar/dotfiles/.config/nvim/deoplete.rc.vim
# '''


[[plugins]]
repo = 'mattn/emmet-vim'
hook_source = '''
  let g:user_emmet_settings = {
    \ 'lang' : 'ja'
  \}
'''

[[plugins]]
repo = 'sophacles/vim-processing'
hook_add = '''
'''

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
hook_add = '''
  let g:cpp_class_scope_highlight = 1
  let g:cpp_member_variable_highlight = 1
  let g:cpp_class_decl_highlight = 1
  let g:cpp_experimental_simple_template_highlight = 1
  let g:cpp_experimental_template_highlight = 1
  let g:cpp_concepts_highlight = 1
  let g:cpp_no_function_highlight = 1
'''

[[plugins]]
repo = 'othree/html5.vim'
hook_add = '''
  let g:html5_event_handler_attributes_complete = 0
	let g:html5_rdfa_attributes_complete = 0
	let g:himl5_microdata_attributes_complete = 0
	let g:html5_aria_attributes_complete = 0
'''

